---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wwimpo/muelleflotante.cl/
    - /bin/cp wp-content/themes/hello-elementor/functions.php $DEPLOYPATH/wp-content/themes/hello-elementor/functions.php
